apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-replication-config
data:
  pg_hba.conf: |
    host replication all 0.0.0.0/0 md5
  postgresql.conf: |
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    pg_shard.enable = on
    pg_pathman.enable = on
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-shard1
spec:
  serviceName: postgres-shard1
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: shard1
  template:
    metadata:
      labels:
        app: postgres
        role: shard1
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PG_SHARD_ENABLE
              value: "1"
            - name: PG_PATHMAN_ENABLE
              value: "1"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: postgres-config
              mountPath: /etc/postgresql
            - name: postgres-replication-config
              mountPath: /etc/postgresql/replication-config
      volumes:
        - name: postgres-replication-config
          configMap:
            name: postgres-replication-config
        - name: postgres-config
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: "managed-csi"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-shard1
spec:
  selector:
    app: postgres
    role: shard1
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-shard2
spec:
  serviceName: shard2
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: shard2
  template:
    metadata:
      labels:
        app: postgres
        role: shard2
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PG_SHARD_ENABLE
              value: "1"
            - name: PG_PATHMAN_ENABLE
              value: "1"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: postgres-config
              mountPath: /etc/postgresql
            - name: postgres-replication-config
              mountPath: /etc/postgresql/replication-config
      volumes:
        - name: postgres-replication-config
          configMap:
            name: postgres-replication-config
        - name: postgres-config
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "managed-csi"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-shard2
spec:
  selector:
    app: postgres
    role: shard2
  ports:
    - protocol: TCP
      port: 5432
