apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: dbcluster
spec:
  serviceName: mongodb
  replicas: 2
  selector:
    matchLabels:
      app: mongo-db
#  strategy:
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: eves
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
          image: mongo:latest
          name: mongo-db
          command: ["/bin/sh"]
          args: ["-c", "mongod --replSet=rs0 --bind_ip_all --dbpath=/data/db"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-storage
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: "managed-csi"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: dbcluster
spec:
  type: LoadBalancer
  ports:
    - name: "mongodb"
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo-express
  name: mongo-express
  namespace: dbcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-express
  template:
    metadata:
      labels:
        name: mongo-express
    spec:
      containers:
        - env:
#            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
#              value: admin
#            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
#              value: admin
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb
          image: mongo-express
          name: mongo-express
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-express
  name: mongo-express
  namespace: dbcluster
spec:
  type: NodePort
  ports:
    - name: "mongoexpress"
      port: 8081
      targetPort: 8081
  selector:
    name: mongo-express
