apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  namespace: dbcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres-app
          image: soorajkumary/databaseapp:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST_READ
              value: postgres-replica
            - name: PGHOST_WRITE
              value: postgres
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              value: postgres
            - name: PGPORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app
  namespace: dbcluster
spec:
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
